spring:
  redis:
    host: localhost
    port: 6379

  profiles:
    active: secret

  h2:
    console:
      enabled: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

